In [4]:
from keras.datasets import mnist
from keras.utils.np_utils import to_categorical

from keras.models import Sequential
from keras.layers import Dense

In [6]:
# data

(X_train, y_train), (X_test, y_test) = mnist.load_data()

# data pre-processing
X_train = X_train.reshape(X_train.shape[0], -1) / 255.   # normalize
X_test = X_test.reshape(X_test.shape[0], -1) / 255.      # normalize
print(y_train[:5])
y_train = to_categorical(y_train, num_classes=10)
print(y_train[:5])
y_test = to_categorical(y_test, num_classes=10)

[5 0 4 1 9]
[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [8]:
# model

model = Sequential()
model.add(Dense(32, input_dim=784, activation="relu"))
model.add(Dense(10, activation="softmax"))
model.compile(optimizer="rmsprop", loss='categorical_crossentropy', metrics=['accuracy'])

model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_3 (Dense)              (None, 32)                25120     
_________________________________________________________________
dense_4 (Dense)              (None, 10)                330       
Total params: 25,450
Trainable params: 25,450
Non-trainable params: 0
_________________________________________________________________


In [9]:
# training

model.fit(X_train, y_train, epochs=2, batch_size=32)


Epoch 1/2
60000/60000 [==============================] - 5s 88us/step - loss: 0.3626 - accuracy: 0.9008
Epoch 2/2
10000/10000 [==============================] - 0s 29us/step
test loss:  0.17228521840050817
test accuracy:  0.9524000287055969


In [ ]:
# testing

loss, accuracy = model.evaluate(X_test, y_test)

print('test loss: ', loss)
print('test accuracy: ', accuracy)

In [ ]:
# save

model.