In [1]:
%%capture
from sklearn.metrics import classification_report

from material.data import *
from ConvTransformer import *


# data

In [2]:
x_train, y_train, x_test, y_test = mnist_data(img=True)
x_train = np.expand_dims(x_train, axis=-1)
x_test = np.expand_dims(x_test, axis=-1)

(60000, 28, 28)
[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
(10000, 28, 28)
[[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]]


# model

In [3]:
model = ConvTransformer()
model.summary()

Model: "ConvTransformer"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
time_distributed (TimeDistri (None, 28, 32)            14496     
_________________________________________________________________
transformer_block (Transform (None, 28, 32)            10656     
_________________________________________________________________
global_average_pooling1d (Gl (None, 32)                0         
_________________________________________________________________
dense_3 (Dense)              (None, 10)                330       
Total params: 25,482
Trainable params: 25,482
Non-trainable params: 0
_________________________________________________________________


In [4]:
# train model
history = model.fit(
    x_train, y_train, 
    batch_size=32, 
    epochs=3, 
    validation_data=(x_test, y_test)
)

Epoch 1/3
1875/1875 [==============================] - 29s 11ms/step - loss: 1.1984 - accuracy: 0.5937 - val_loss: 0.5796 - val_accuracy: 0.8144
Epoch 2/3
1875/1875 [==============================] - 19s 10ms/step - loss: 0.5579 - accuracy: 0.8183 - val_loss: 0.5011 - val_accuracy: 0.8383
Epoch 3/3
1875/1875 [==============================] - 19s 10ms/step - loss: 0.4586 - accuracy: 0.8518 - val_loss: 0.4186 - val_accuracy: 0.8650


In [5]:
y_pred = model.predict(x_test, verbose=True)
y_pred = np.argmax(y_pred, axis=-1)
y_test = np.argmax(y_test, axis=-1)
print(classification_report(y_test, y_pred))

313/313 [==============================] - 2s 4ms/step


'              precision    recall  f1-score   support\n\n           0       0.95      0.95      0.95       980\n           1       0.96      0.98      0.97      1135\n           2       0.82      0.63      0.71      1032\n           3       0.81      0.91      0.86      1010\n           4       0.82      0.92      0.86       982\n           5       0.76      0.85      0.80       892\n           6       0.92      0.86      0.89       958\n           7       0.85      0.85      0.85      1028\n           8       0.87      0.94      0.91       974\n           9       0.90      0.76      0.82      1009\n\n    accuracy                           0.86     10000\n   macro avg       0.87      0.86      0.86     10000\nweighted avg       0.87      0.86      0.86     10000\n'