In [60]:
import tensorflow as tf
from tensorflow.keras.layers import Layer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.layers import Embedding, Masking, Lambda, LSTM, Input
from tensorflow.keras.models import Model

In [61]:
raw_inputs = [
    [711, 632, 71],
    [73, 8, 3215, 55, 927],
    [83, 91, 1, 645, 1253, 927],
]

padded_inputs = pad_sequences(raw_inputs, padding="post")
print(padded_inputs)


[[ 711  632   71    0    0    0]
 [  73    8 3215   55  927    0]
 [  83   91    1  645 1253  927]]


# ------------------------------------------------------------------
# method 1: use support masking layer

In [62]:
embedding = Embedding(input_dim=5000, output_dim=2, mask_zero=True)
masked_output = embedding(padded_inputs)
print(masked_output[0])
# ??? not working ???

tf.Tensor(
[[-0.03207723  0.00389638]
 [ 0.03401626 -0.01618049]
 [-0.01414819  0.02728978]
 [ 0.01018701 -0.02727596]
 [ 0.01018701 -0.02727596]
 [ 0.01018701 -0.02727596]], shape=(6, 2), dtype=float32)


# ------------------------------------------------------------------
# method 2: use masking layer

In [63]:
# Simulate the embedding lookup by expanding the 2D input to 3D,
# with embedding dimension of 2.
SimEmbedding = Lambda(lambda inputs: tf.cast(
    tf.tile(tf.expand_dims(inputs, axis=-1), [1, 1, 2]), tf.float32
))

masked_output = SimEmbedding(padded_inputs)
print(masked_output[0])

tf.Tensor(
[[711. 711.]
 [632. 632.]
 [ 71.  71.]
 [  0.   0.]
 [  0.   0.]
 [  0.   0.]], shape=(6, 2), dtype=float32)


In [64]:
masking_layer = Masking()
masked_embedding = masking_layer(masked_output)
print(type(masked_output))

<class 'tensorflow.python.framework.ops.EagerTensor'>
