In [6]:
%%capture
import torch
from torch.nn.init import normal_
from torch.autograd import Variable
import torch.optim as optim

In [17]:
x = torch.empty(1, requires_grad=True)
normal_(x)
print(x)

tensor([0.3177], requires_grad=True)


In [18]:
# create function to optimize
y = 2 * x
print(y)

# calculate the gradient and feed it back
print(x.grad)
y.backward()
print(x.grad)


tensor([0.6353], grad_fn=<MulBackward0>)
None
tensor([2.])


In [19]:
optimizer = optim.Adam([x], lr=0.1)

y = 2 * x
print(x)

optimizer.zero_grad()
y.backward()
optimizer.step()

print(x)

tensor([0.3177], requires_grad=True)
tensor([0.2177], requires_grad=True)


In [20]:
# 1. basic train
# data:
datagen = zip([torch.rand(1, 4) for _ in range(12)], [torch.zeros(1) for _ in range(12)])

# variable(weights)
W = Variable(torch.randn(4, 1), requires_grad=True)
b = Variable(torch.randn(1), requires_grad=True)
model = lambda x: torch.matmul(x, W) + b

optimizer = optim.Adam([W, b])

for x, y in datagen:
    optimizer.zero_grad()

    pred = model(x)
    loss = (pred - y) ** 2

    loss.backward()
    optimizer.step()

    print(loss)


tensor([[2.1882]], grad_fn=<PowBackward0>)
tensor([[3.3360]], grad_fn=<PowBackward0>)
tensor([[1.3381]], grad_fn=<PowBackward0>)
tensor([[1.2334]], grad_fn=<PowBackward0>)
tensor([[5.4903]], grad_fn=<PowBackward0>)
tensor([[1.2010]], grad_fn=<PowBackward0>)
tensor([[1.8789]], grad_fn=<PowBackward0>)
tensor([[2.2155]], grad_fn=<PowBackward0>)
tensor([[3.2401]], grad_fn=<PowBackward0>)
tensor([[2.0514]], grad_fn=<PowBackward0>)
tensor([[1.6296]], grad_fn=<PowBackward0>)
tensor([[3.1413]], grad_fn=<PowBackward0>)


# initialization

In [2]:
x = torch.empty(5, 3)
print("empty", x)

x = torch.rand(5, 3)
print("rand", x)

x = torch.zeros(5, 3, dtype=torch.long)
print("zeros", x)

x = torch.tensor([5.5, 3])
print(x)

empty tensor([[-8.5232e-22,  4.5845e-41, -8.5232e-22],
        [ 4.5845e-41,  4.9961e+20,  4.5845e-41],
        [-4.0814e-29,  4.5845e-41, -4.0814e-29],
        [ 4.5845e-41, -8.8401e-29,  4.5845e-41],
        [ 5.1762e+20,  4.5845e-41,  5.1762e+20]])
rand tensor([[0.9213, 0.8025, 0.9229],
        [0.6111, 0.4490, 0.3283],
        [0.7732, 0.3911, 0.9300],
        [0.1198, 0.0873, 0.8795],
        [0.0815, 0.5245, 0.4016]])
zeros tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
tensor([5.5000, 3.0000])


In [3]:
# additional

## from numpy
a = np.ones(5)
b = torch.from_numpy(a)
print(b)
print(b.numpy())

## from torch tensor
x = torch.randn_like(b, dtype=torch.float)    # override dtype!
print(x)

# x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
# print(x)

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[1. 1. 1. 1. 1.]
tensor([-0.2367, -0.4702, -0.1085, -0.2559,  1.6535])


# operation

In [5]:
# one element
x = torch.randn(4, 4)
y = x.view(16)    # : reshape
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [6]:
x = torch.rand(5, 3)
y = torch.rand(5, 3)
z = torch.add(x,y)
print(z)

tensor([[1.2781, 1.2587, 0.3948],
        [0.3611, 1.3786, 1.5138],
        [1.3472, 1.1214, 1.0918],
        [0.6161, 1.2757, 0.5494],
        [0.4003, 1.6258, 1.7759]])


# get gradient

In [13]:
x = torch.ones(1, 2, requires_grad=True)
y = torch.matmul(x, x.T)
print(y.grad_fn)
y.backward()
print(x.grad)   # grad is more like delta x

tensor([[2., 2.]])
